#!/usr/bin/env python3
import os
import sys
import json
import argparse
from pathlib import Path

def parse_args():
    parser = argparse.ArgumentParser(description="PRISM Sentinel Audit Packager")
    parser.add_argument('--target-project', type=str, help='Path to target project')
    parser.add_argument('positional_target', nargs='?', type=str, help='Path to target project (positional)')
    args = parser.parse_args()
    
    target = args.target_project or args.positional_target
    return Path(target).resolve() if target else None

def main():
    try:
        target_project = parse_args()
        print("PRISM Sentinel Audit Packager starting...")
        
        reports_dir = Path(os.environ.get("SENTINEL_REPORTS_DIR", "reports"))
        reports_dir.mkdir(exist_ok=True)
        
        package_path = reports_dir / "audit_evidence_package.md"
        
        report_files = [
            "requirements_traceability.md",
            "gap_analysis.md",
            "code_quality_report.md",
            "environment_validation.md",
            "gcs_audit.md"
        ]
        
        with open(package_path, "w") as out_f:
            out_f.write("# PRISM Sentinel - Audit Evidence Package\n\n")
            out_f.write("## Executive Summary\n")
            out_f.write("This package compiles all verification and assurance reports generated by PRISM Sentinel.\n")
            if target_project:
                out_f.write(f"Target Project: {target_project}\n")
            out_f.write("\n")
            
            for report_name in report_files:
                report_file = reports_dir / report_name
                if report_file.exists():
                    out_f.write(f"## {report_name.replace('.md', '').replace('_', ' ').title()}\n\n")
                    try:
                        content = report_file.read_text()
                        # Strip top-level header to avoid nested markdown issues
                        lines = content.splitlines()
                        if lines and lines[0].startswith("# "):
                            lines = lines[1:]
                        out_f.write("\n".join(lines) + "\n\n")
                    except Exception as e:
                        out_f.write(f"Error reading report {report_name}: {e}\n\n")
                else:
                    out_f.write(f"## {report_name.replace('.md', '').replace('_', ' ').title()}\n\n")
                    out_f.write(f"⚠️ Report {report_name} was not generated.\n\n")
                    
        print(f"Audit evidence package generated successfully at {package_path}")
    except Exception as e:
        print(f"Critical failure in audit packager: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
